import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import categoryRoutes from './category.routes';
import brandRoutes from './brand.routes';
import productRoutes from './product.routes';
import cartRoutes from './cart.routes';
import wishlistRoutes from './wishlist.routes';
import customizationRoutes from './customization.routes';
import checkoutRoutes from './checkout.routes';
import paymentRoutes from './payment.routes';
import orderRoutes from './order.routes';
import productionRoutes from './production.routes';
import quotationRoutes from './quotation.routes';
import settingsRoutes from './settings.routes';
import supportRoutes from './support.routes';
import adminDashboardRoutes from './adminDashboard.routes';
import dealerDashboardRoutes from './dealerDashboard.routes';
import reportsRoutes from './reports.routes';
import schoolAddressRoutes from './schoolAddress.routes';
import shippingRoutes from './shipping.routes';
import dealerDirectoryRoutes from './dealerDirectory.routes';
import kitRoutes from './kit.routes';
import schoolAccountRoutes from './schoolAccount.routes';
import faqRoutes from './faq.routes';
import notificationRoutes from './notification.routes';
import uploadRoutes from './upload.routes';
import adminOrderRoutes from './adminOrder.routes';
import adminSchoolRoutes from './adminSchool.routes';
import adminDealerRoutes from './adminDealer.routes';
import adminPaymentRoutes from './adminPayment.routes';
import adminInvoiceRoutes from './adminInvoice.routes';
import adminRbacRoutes from './adminRbac.routes';
import adminSettingsRoutes from './adminSettings.routes';
import adminWhatsappRoutes from './adminWhatsapp.routes';
import whatsappWebhookRoutes from './whatsappWebhook.routes';
import auditRoutes from './audit.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/categories', categoryRoutes);
router.use('/brands', brandRoutes);
router.use('/products', productRoutes);
router.use('/cart', cartRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/customization-requests', customizationRoutes);
router.use('/checkout', checkoutRoutes);
router.use('/payments', paymentRoutes);
router.use('/orders', orderRoutes);
router.use('/orders', productionRoutes);
router.use('/quotation-requests', quotationRoutes);
router.use('/settings', settingsRoutes);
router.use('/support', supportRoutes);
router.use('/admin/dashboard', adminDashboardRoutes);
router.use('/dealer', dealerDashboardRoutes);
router.use('/reports', reportsRoutes);
router.use('/addresses', schoolAddressRoutes);
router.use('/shipping-methods', shippingRoutes);
router.use('/dealers', dealerDirectoryRoutes);
router.use('/kits', kitRoutes);
router.use('/schools', schoolAccountRoutes);
router.use('/faqs', faqRoutes);
router.use('/notifications', notificationRoutes);
router.use('/uploads', uploadRoutes);
router.use('/admin/orders', adminOrderRoutes);
router.use('/admin/schools', adminSchoolRoutes);
router.use('/admin/dealers', adminDealerRoutes);
router.use('/admin/payments', adminPaymentRoutes);
router.use('/admin/invoices', adminInvoiceRoutes);
router.use('/admin/settings', adminSettingsRoutes);
router.use('/admin/whatsapp', adminWhatsappRoutes);
router.use('/webhooks/whatsapp', whatsappWebhookRoutes);
router.use('/admin', adminRbacRoutes);
router.use('/audit-logs', auditRoutes);

export default router;
